version: '3.7'

services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:3.1
    ports:
      - 9411:9411

  jaeger:
    image: jaegertracing/all-in-one:1.54.0
    container_name: jaeger
    ports:
      - 6832:6832/udp
      - 4318:4318
      - 16686:16686

  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    extra_hosts:
    - "host.docker.internal:host-gateway"