global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'microservice'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'host.docker.internal:9464'
        - 'host.docker.internal:9465'