global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'microservice'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']

rule_files:
    - '/etc/prometheus/alerting_rules.yml' 

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']