global:
  resolve_timeout: 5m 

route:
  group_by: ['service_name'] 
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 30m
  receiver: 'demo-webhook'

receivers:
- name: 'demo-webhook'
  webhook_configs:
    - url: 'http://webhook:8080/json-hook'
